services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    environment:
      - PORT=${PORT:-8000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/info/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    container_name: folio-api

  caddy:
    image: caddy:latest
    ports:
      - "${WEB_PORT:-80}:80"
      - "443:443"
    environment:
      - PORT=${PORT:-8000}
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./logs/caddy:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped
    container_name: folio-caddy

volumes:
  caddy_data:
  caddy_config: